# Generated by Django 4.2.8 on 2023-12-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('local_date', models.DateField()),
                ('local_time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
